


server:
  servlet:
    context-path: /order
  port: 9999
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
mybatis-plus:
#  mapper-locations: cn/edu/transportsys/mapper/*.xml
  type-aliases-package: cn.edu.yzx.order.entity
